"""
ddl.py — DDL des 4 niveaux de l'architecture ETL Télécom.

  Niveau 1 : RAW_MMG / RAW_OCC         — copie exacte du fichier brut
  Niveau 2 : DETAIL_MMG / DETAIL_OCC   — après transformations
  Niveau 3 : AGG_MMG / AGG_OCC         — agrégé par abonné + date + service
  Niveau 4 : DIM_* + FACT_REVENUS      — Data Warehouse étoile
"""

import cx_Oracle

from config import ORACLE_SCHEMA, log
from db import tbl, table_exists, is_ora_error


# ── Niveau 1 : RAW ─────────────────────────────────────────────
DDL_RAW = {
    "RAW_MMG": """
        CREATE TABLE {t} (
            raw_id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fichier_source        VARCHAR2(255),
            etl_chargement        TIMESTAMP DEFAULT SYSTIMESTAMP,
            AGGREGATION_GROUP     VARCHAR2(50),
            APN                   VARCHAR2(100),
            A_IMSI                VARCHAR2(50),
            A_MSISDN              VARCHAR2(50),
            A_MSISDN_ORIG         VARCHAR2(50),
            BEARER_SERVICE        VARCHAR2(20),
            B_DATASOURCE          VARCHAR2(50),
            B_IMSI                VARCHAR2(50),
            B_MSISDN              VARCHAR2(50),
            B_MSISDN_ORIG         VARCHAR2(50),
            CALL_REFERENCE        VARCHAR2(50),
            CALL_TYPE             VARCHAR2(20),
            CAUSE_FOR_CLOSING     VARCHAR2(20),
            CDR_SEARCH_DETAIL_ID  VARCHAR2(50),
            CELL_ID               VARCHAR2(50),
            CGI_ID_KEY            VARCHAR2(100),
            CHARGE_AMNT_STEP      VARCHAR2(30),
            CHARGE_AMOUNT_ORIG    VARCHAR2(30),
            C_NUM                 VARCHAR2(50),
            C_NUM_ORIG            VARCHAR2(50),
            DATA_VOLUME           VARCHAR2(30),
            DATA_VOLUME_DOWN      VARCHAR2(30),
            DATA_VOLUME_UP        VARCHAR2(30),
            DURATION_STEP         VARCHAR2(20),
            ESTIMATED_AMOUNT      VARCHAR2(30),
            EVENT_DURATION        VARCHAR2(20),
            EVENT_STATUS          VARCHAR2(20),
            EVENT_TYPE            VARCHAR2(20),
            EVENT_TYPE_ORIG       VARCHAR2(20),
            FILENAME              VARCHAR2(255),
            FILTER_CODE           VARCHAR2(20),
            IMEI                  VARCHAR2(50),
            LAST_PARTIAL          VARCHAR2(5),
            NE                    VARCHAR2(20),
            ORIG_START_TIME       VARCHAR2(30),
            PARTIAL_SEQ_ID        VARCHAR2(10),
            PARTNER               VARCHAR2(100),
            PARTNER_CODE          VARCHAR2(50),
            PGW_ADDRESS           VARCHAR2(50),
            PRICE_PLAN_CODE       VARCHAR2(50),
            PROC_DATE             VARCHAR2(30),
            PROC_HOUR             VARCHAR2(10),
            RADIO_TYPE            VARCHAR2(20),
            RATE_CODE             VARCHAR2(50),
            RECORD_ID             VARCHAR2(50),
            RECORD_STATUS         VARCHAR2(20),
            RECORD_TYPE           VARCHAR2(20),
            ROAMING_TYPE          VARCHAR2(10),
            SERVED_MSRN           VARCHAR2(50),
            SERVICE_ID            VARCHAR2(50),
            SERVICE_PARTNER       VARCHAR2(100),
            SERVICE_TYPE          VARCHAR2(50),
            SGSN_ADDRESS          VARCHAR2(50),
            SMS_CENTRE            VARCHAR2(50),
            START_DATE_TIME_HOME  VARCHAR2(30),
            START_TIME            VARCHAR2(30),
            SUBSCRIBER_TYPE       VARCHAR2(30),
            TELESERVICE           VARCHAR2(20),
            TEST_FLAG             VARCHAR2(5),
            TON_A                 VARCHAR2(5),
            TON_B                 VARCHAR2(5),
            TON_C                 VARCHAR2(5),
            TRAFFIC_TYPE          VARCHAR2(20),
            TRUNK_IN              VARCHAR2(50),
            TRUNK_OUT             VARCHAR2(50)
        )""",
    "RAW_OCC": """
        CREATE TABLE {t} (
            raw_id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fichier_source        VARCHAR2(255),
            etl_chargement        TIMESTAMP DEFAULT SYSTIMESTAMP,
            AGGREGATION_GROUP     VARCHAR2(50),
            APN                   VARCHAR2(100),
            A_IMSI                VARCHAR2(50),
            A_MSISDN              VARCHAR2(50),
            A_MSISDN_ORIG         VARCHAR2(50),
            BEARER_SERVICE        VARCHAR2(20),
            B_DATASOURCE          VARCHAR2(50),
            B_IMSI                VARCHAR2(50),
            B_MSISDN              VARCHAR2(50),
            B_MSISDN_ORIG         VARCHAR2(50),
            CALL_REFERENCE        VARCHAR2(50),
            CALL_TYPE             VARCHAR2(20),
            CAUSE_FOR_CLOSING     VARCHAR2(20),
            CDR_SEARCH_DETAIL_ID  VARCHAR2(50),
            CELL_ID               VARCHAR2(50),
            CGI_ID_KEY            VARCHAR2(100),
            CHARGE_AMNT_STEP      VARCHAR2(30),
            CHARGE_AMOUNT_ORIG    VARCHAR2(30),
            C_NUM                 VARCHAR2(50),
            C_NUM_ORIG            VARCHAR2(50),
            DATA_VOLUME           VARCHAR2(30),
            DATA_VOLUME_DOWN      VARCHAR2(30),
            DATA_VOLUME_UP        VARCHAR2(30),
            DURATION_STEP         VARCHAR2(20),
            ESTIMATED_AMOUNT      VARCHAR2(30),
            EVENT_DURATION        VARCHAR2(20),
            EVENT_STATUS          VARCHAR2(20),
            EVENT_TYPE            VARCHAR2(20),
            EVENT_TYPE_ORIG       VARCHAR2(20),
            FILENAME              VARCHAR2(255),
            FILTER_CODE           VARCHAR2(20),
            IMEI                  VARCHAR2(50),
            LAST_PARTIAL          VARCHAR2(5),
            NE                    VARCHAR2(20),
            ORIG_START_TIME       VARCHAR2(30),
            PARTIAL_SEQ_ID        VARCHAR2(10),
            PARTNER               VARCHAR2(100),
            PARTNER_CODE          VARCHAR2(50),
            PGW_ADDRESS           VARCHAR2(50),
            PRICE_PLAN_CODE       VARCHAR2(50),
            PROC_DATE             VARCHAR2(30),
            PROC_HOUR             VARCHAR2(10),
            RADIO_TYPE            VARCHAR2(20),
            RATE_CODE             VARCHAR2(50),
            RECORD_ID             VARCHAR2(50),
            RECORD_STATUS         VARCHAR2(20),
            RECORD_TYPE           VARCHAR2(20),
            ROAMING_TYPE          VARCHAR2(10),
            SERVED_MSRN           VARCHAR2(50),
            SERVICE_ID            VARCHAR2(50),
            SERVICE_PARTNER       VARCHAR2(100),
            SERVICE_TYPE          VARCHAR2(50),
            SGSN_ADDRESS          VARCHAR2(50),
            SMS_CENTRE            VARCHAR2(50),
            START_DATE_TIME_HOME  VARCHAR2(30),
            START_TIME            VARCHAR2(30),
            SUBSCRIBER_TYPE       VARCHAR2(30),
            TELESERVICE           VARCHAR2(20),
            TEST_FLAG             VARCHAR2(5),
            TON_A                 VARCHAR2(5),
            TON_B                 VARCHAR2(5),
            TON_C                 VARCHAR2(5),
            TRAFFIC_TYPE          VARCHAR2(20),
            TRUNK_IN              VARCHAR2(50),
            TRUNK_OUT             VARCHAR2(50)
        )""",
}


# Structure alignée sur les tables de production Tunisie Telecom :
#   MMG : RA_T_MMG_CDR_DETAIL
#   OCC : RA_T_OCC_CDR_DETAIL
DDL_DETAIL = {
    "DETAIL_MMG": """
        CREATE TABLE {t} (
            detail_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fichier_source    VARCHAR2(255),
            etl_chargement    TIMESTAMP DEFAULT SYSTIMESTAMP,
            NE                VARCHAR2(50),
            A_MSISDN          VARCHAR2(50),
            B_MSISDN          VARCHAR2(50),
            START_DATE        DATE,
            START_HOUR        NUMBER(10,0),
            EVENT_TYPE        VARCHAR2(50),
            EVENT_TYPE_ORIG   VARCHAR2(50),
            CALL_TYPE         VARCHAR2(50),
            EVENT_STATUS      VARCHAR2(50),
            SUBSCRIBER_TYPE   VARCHAR2(50),
            SERVICE_TYPE      VARCHAR2(50),
            ORIG_START_TIME   VARCHAR2(30)
        )""",
    "DETAIL_OCC": """
        CREATE TABLE {t} (
            detail_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fichier_source    VARCHAR2(255),
            etl_chargement    TIMESTAMP DEFAULT SYSTIMESTAMP,
            DATASOURCE        VARCHAR2(20),
            A_MSISDN          VARCHAR2(200),
            B_MSISDN          VARCHAR2(200),
            START_DATE        DATE,
            START_HOUR        NUMBER(3,0),
            APN               VARCHAR2(50),
            CALL_TYPE         VARCHAR2(20),
            EVENT_TYPE        VARCHAR2(20),
            SUBSCRIBER_TYPE   VARCHAR2(30),
            ROAMING_TYPE      VARCHAR2(10),
            PARTNER           VARCHAR2(20),
            CHARGE_AMOUNT     NUMBER(20,5),
            KEYWORD           VARCHAR2(100),
            ORIG_START_TIME   VARCHAR2(70)
        )""",
}

# ── Niveau 3 : AGG ─────────────────────────────────────────────
# Structure alignée sur le format des fichiers agrégés Tunisie Telecom
DDL_AGG = {
    "AGG_MMG": """
        CREATE TABLE {t} (
            agg_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            etl_chargement  TIMESTAMP DEFAULT SYSTIMESTAMP,
            fichier_source  VARCHAR2(255),
            B_MSISDN        VARCHAR2(50)   NOT NULL,
            START_DATE      DATE           NOT NULL,
            START_HOUR      NUMBER(10,0)   NOT NULL,
            CALL_TYPE       VARCHAR2(50),
            EVENT_TYPE      VARCHAR2(50),
            EVENT_STATUS    VARCHAR2(50),
            SUBSCRIBER_TYPE VARCHAR2(50),
            SERVICE_TYPE    VARCHAR2(50),
            CDR_COUNT       NUMBER         DEFAULT 0,
            CONSTRAINT uq_agg_mmg UNIQUE (B_MSISDN, START_DATE, START_HOUR, EVENT_TYPE, SERVICE_TYPE)
        )""",
    "AGG_OCC": """
        CREATE TABLE {t} (
            agg_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            etl_chargement  TIMESTAMP DEFAULT SYSTIMESTAMP,
            fichier_source  VARCHAR2(255),
            B_MSISDN        VARCHAR2(200)  NOT NULL,
            START_DATE      DATE           NOT NULL,
            START_HOUR      NUMBER(3,0)    NOT NULL,
            CALL_TYPE       VARCHAR2(20),
            EVENT_TYPE      VARCHAR2(20),
            SUBSCRIBER_TYPE VARCHAR2(30),
            KEYWORD         VARCHAR2(100),
            CDR_COUNT       NUMBER         DEFAULT 0,
            CHARGE_AMOUNT   NUMBER(20,5)   DEFAULT 0,
            CONSTRAINT uq_agg_occ UNIQUE (B_MSISDN, START_DATE, START_HOUR, EVENT_TYPE, KEYWORD)
        )""",
}

# ── Niveau 4 : Data Warehouse ──────────────────────────────────
DDL_DW = {
    "DIM_TEMPS": """
        CREATE TABLE {t} (
            date_id     NUMBER PRIMARY KEY,
            full_date   DATE NOT NULL,
            year        NUMBER(4) NOT NULL,
            month       NUMBER(2) NOT NULL,
            month_name  VARCHAR2(20),
            day         NUMBER(2) NOT NULL,
            day_name    VARCHAR2(20),
            hour        NUMBER(2) NOT NULL,
            week        NUMBER(2),
            quarter     NUMBER(1),
            is_weekend  VARCHAR2(1) DEFAULT 'N'
        )""",
    "DIM_ABONNE": """
        CREATE TABLE {t} (
            abonne_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            msisdn          VARCHAR2(20) UNIQUE NOT NULL,
            subscriber_type VARCHAR2(30),
            imei            VARCHAR2(50),
            first_seen      DATE,
            last_seen       DATE,
            total_volume_mo NUMBER(18,4) DEFAULT 0,
            total_sms       NUMBER       DEFAULT 0,
            total_revenue   NUMBER(18,6) DEFAULT 0
        )""",
    "DIM_SERVICE": """
        CREATE TABLE {t} (
            service_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            keyword          VARCHAR2(50)  NOT NULL,
            nom_service      VARCHAR2(100),
            nom_fournisseur  VARCHAR2(100),
            numero_court     VARCHAR2(20),
            type_service     VARCHAR2(50),
            prix             NUMBER(10,4),
            CONSTRAINT uq_svc UNIQUE (keyword)
        )""",
    "DIM_FOURNISSEUR": """
        CREATE TABLE {t} (
            fournisseur_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            provider_name    VARCHAR2(100) UNIQUE NOT NULL,
            nationalite      VARCHAR2(50),
            id_fiscale       VARCHAR2(50),
            adresse          VARCHAR2(255),
            etl_chargement   TIMESTAMP DEFAULT SYSTIMESTAMP
        )""",
    "FACT_REVENUS": """
        CREATE TABLE {t} (
            fact_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date_id         NUMBER,
            abonne_id       NUMBER,
            service_id      NUMBER,
            fournisseur_id  NUMBER,
            data_volume_mo  NUMBER(18,4) DEFAULT 0,
            data_revenue    NUMBER(18,6) DEFAULT 0,
            session_count   NUMBER       DEFAULT 0,
            session_dur_sec NUMBER(18)   DEFAULT 0,
            sms_count       NUMBER       DEFAULT 0,
            sms_success     NUMBER       DEFAULT 0,
            sms_failed      NUMBER       DEFAULT 0,
            sms_mo          NUMBER       DEFAULT 0,
            sms_mt          NUMBER       DEFAULT 0,
            sms_revenue     NUMBER(18,6) DEFAULT 0,
            total_revenue   NUMBER(18,6) DEFAULT 0,
            etl_source      VARCHAR2(255),
            etl_chargement  TIMESTAMP DEFAULT SYSTIMESTAMP,
            CONSTRAINT uq_fact UNIQUE (date_id, abonne_id, service_id)
        )""",
    "ETL_LOG": """
        CREATE TABLE {t} (
            id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_date       TIMESTAMP DEFAULT SYSTIMESTAMP,
            source         VARCHAR2(50),
            fichier        VARCHAR2(255),
            niveau         VARCHAR2(20),
            lignes_entree  NUMBER,
            lignes_sortie  NUMBER,
            statut         VARCHAR2(20),
            message        VARCHAR2(2000)
        )""",
}


def init_all_tables(conn) -> None:
    """Crée toutes les tables (RAW -> DETAIL -> AGG -> DW) si absentes."""
    cur = conn.cursor()
    all_ddl = {**DDL_RAW, **DDL_DETAIL, **DDL_AGG, **DDL_DW}

    for name, ddl in all_ddl.items():
        full = tbl(name)
        if not table_exists(cur, full):
            try:
                cur.execute(ddl.format(t=full))
                conn.commit()
                log.info(f"  Table créée  : {full}")
            except cx_Oracle.DatabaseError as e:
                if not is_ora_error(e, 955):
                    log.error(f"  Erreur {full} : {e}")
                    raise
        else:
            log.info(f"  Table existe : {full}")

    # Index sur FACT_REVENUS et tables AGG
    fact_full = tbl("FACT_REVENUS")
    px = ORACLE_SCHEMA.lower() + "_" if ORACLE_SCHEMA else ""
    for idx, col in [
        (f"{px}idx_fact_date",    f"{fact_full}(date_id)"),
        (f"{px}idx_fact_abonne",  f"{fact_full}(abonne_id)"),
        (f"{px}idx_fact_service", f"{fact_full}(service_id)"),
        (f"{px}idx_agg_mmg_ms",   f"{tbl('AGG_MMG')}(B_MSISDN, START_DATE)"),
        (f"{px}idx_agg_occ_ms",   f"{tbl('AGG_OCC')}(B_MSISDN, START_DATE)"),
    ]:
        try:
            cur.execute(f"CREATE INDEX {idx} ON {col}")
            conn.commit()
        except cx_Oracle.DatabaseError as e:
            if not is_ora_error(e, 955):
                log.warning(f"  Index {idx} : {e}")

    cur.close()
    log.info("  Infrastructure complète prête.")
